# Generated by Django 2.0.6 on 2018-07-04 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('q1', models.IntegerField(blank=True, default=None, null=True)),
                ('q2', models.IntegerField(blank=True, default=None, null=True)),
                ('q3', models.IntegerField(blank=True, default=None, null=True)),
                ('q4', models.IntegerField(blank=True, default=None, null=True)),
                ('q5', models.IntegerField(blank=True, default=None, null=True)),
                ('q6', models.IntegerField(blank=True, default=None, null=True)),
                ('q7', models.IntegerField(blank=True, default=None, null=True)),
                ('q8', models.IntegerField(blank=True, default=None, null=True)),
                ('q9', models.IntegerField(blank=True, default=None, null=True)),
                ('q10', models.IntegerField(blank=True, default=None, null=True)),
                ('score', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'AR',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('course', models.CharField(choices=[('IOT', 'IOT'), ('Ethical Hacking', 'Ethical Hacking'), ('Augmented Reality', 'Augmented Reality'), ('Machine Learning', 'Machine Learning')], max_length=30)),
                ('score', models.IntegerField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('q1', models.IntegerField(blank=True, default=None, null=True)),
                ('q2', models.IntegerField(blank=True, default=None, null=True)),
                ('q3', models.IntegerField(blank=True, default=None, null=True)),
                ('q4', models.IntegerField(blank=True, default=None, null=True)),
                ('q5', models.IntegerField(blank=True, default=None, null=True)),
                ('q6', models.IntegerField(blank=True, default=None, null=True)),
                ('q7', models.IntegerField(blank=True, default=None, null=True)),
                ('q8', models.IntegerField(blank=True, default=None, null=True)),
                ('q9', models.IntegerField(blank=True, default=None, null=True)),
                ('q10', models.IntegerField(blank=True, default=None, null=True)),
                ('score', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'EH',
            },
        ),
        migrations.CreateModel(
            name='IOT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('q1', models.IntegerField(blank=True, default=None, null=True)),
                ('q2', models.IntegerField(blank=True, default=None, null=True)),
                ('q3', models.IntegerField(blank=True, default=None, null=True)),
                ('q4', models.IntegerField(blank=True, default=None, null=True)),
                ('q5', models.IntegerField(blank=True, default=None, null=True)),
                ('q6', models.IntegerField(blank=True, default=None, null=True)),
                ('q7', models.IntegerField(blank=True, default=None, null=True)),
                ('q8', models.IntegerField(blank=True, default=None, null=True)),
                ('q9', models.IntegerField(blank=True, default=None, null=True)),
                ('q10', models.IntegerField(blank=True, default=None, null=True)),
                ('score', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'IOT',
            },
        ),
        migrations.CreateModel(
            name='ML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('q1', models.IntegerField(blank=True, default=None, null=True)),
                ('q2', models.IntegerField(blank=True, default=None, null=True)),
                ('q3', models.IntegerField(blank=True, default=None, null=True)),
                ('q4', models.IntegerField(blank=True, default=None, null=True)),
                ('q5', models.IntegerField(blank=True, default=None, null=True)),
                ('q6', models.IntegerField(blank=True, default=None, null=True)),
                ('q7', models.IntegerField(blank=True, default=None, null=True)),
                ('q8', models.IntegerField(blank=True, default=None, null=True)),
                ('q9', models.IntegerField(blank=True, default=None, null=True)),
                ('q10', models.IntegerField(blank=True, default=None, null=True)),
                ('score', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'ML',
            },
        ),
    ]
