# Generated by Django 2.0.6 on 2018-06-19 16:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0003_auto_20180619_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True),
        ),
    ]
