# Generated by Django 2.0.6 on 2018-06-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0005_auto_20180620_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='course',
            field=models.CharField(choices=[('IOT', 'IOT'), ('Robotics', 'Robotics'), ('Android', 'Android')], default='IOT', max_length=30),
            preserve_default=False,
        ),
    ]
