# Generated by Django 2.0.6 on 2018-06-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0006_detail_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='course',
            field=models.CharField(choices=[('IOT', 'IOT'), ('Ethical Hacking', 'Ethical Hacking'), ('Augmented Reality', 'Augmented Reality'), ('Machine Learning', 'Machine Learning')], max_length=30),
        ),
    ]
