# Generated by Django 2.0.6 on 2018-06-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0007_auto_20180620_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
