# Generated by Django 2.0.6 on 2018-06-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0009_detail_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('q1', models.IntegerField(blank=True, default=None, null=True)),
                ('q2', models.IntegerField(blank=True, default=None, null=True)),
                ('q3', models.IntegerField(blank=True, default=None, null=True)),
                ('q4', models.IntegerField(blank=True, default=None, null=True)),
                ('q5', models.IntegerField(blank=True, default=None, null=True)),
                ('q6', models.IntegerField(blank=True, default=None, null=True)),
                ('q7', models.IntegerField(blank=True, default=None, null=True)),
                ('q8', models.IntegerField(blank=True, default=None, null=True)),
                ('q9', models.IntegerField(blank=True, default=None, null=True)),
                ('q10', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
