# Generated by Django 2.0.6 on 2018-06-30 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0010_iot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iot',
            name='phone',
        ),
    ]
