# Generated by Django 2.0.6 on 2018-06-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0011_remove_iot_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('q1', models.IntegerField(blank=True, default=None, null=True)),
                ('q2', models.IntegerField(blank=True, default=None, null=True)),
                ('q3', models.IntegerField(blank=True, default=None, null=True)),
                ('q4', models.IntegerField(blank=True, default=None, null=True)),
                ('q5', models.IntegerField(blank=True, default=None, null=True)),
                ('q6', models.IntegerField(blank=True, default=None, null=True)),
                ('q7', models.IntegerField(blank=True, default=None, null=True)),
                ('q8', models.IntegerField(blank=True, default=None, null=True)),
                ('q9', models.IntegerField(blank=True, default=None, null=True)),
                ('q10', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('q1', models.IntegerField(blank=True, default=None, null=True)),
                ('q2', models.IntegerField(blank=True, default=None, null=True)),
                ('q3', models.IntegerField(blank=True, default=None, null=True)),
                ('q4', models.IntegerField(blank=True, default=None, null=True)),
                ('q5', models.IntegerField(blank=True, default=None, null=True)),
                ('q6', models.IntegerField(blank=True, default=None, null=True)),
                ('q7', models.IntegerField(blank=True, default=None, null=True)),
                ('q8', models.IntegerField(blank=True, default=None, null=True)),
                ('q9', models.IntegerField(blank=True, default=None, null=True)),
                ('q10', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('q1', models.IntegerField(blank=True, default=None, null=True)),
                ('q2', models.IntegerField(blank=True, default=None, null=True)),
                ('q3', models.IntegerField(blank=True, default=None, null=True)),
                ('q4', models.IntegerField(blank=True, default=None, null=True)),
                ('q5', models.IntegerField(blank=True, default=None, null=True)),
                ('q6', models.IntegerField(blank=True, default=None, null=True)),
                ('q7', models.IntegerField(blank=True, default=None, null=True)),
                ('q8', models.IntegerField(blank=True, default=None, null=True)),
                ('q9', models.IntegerField(blank=True, default=None, null=True)),
                ('q10', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
