# Generated by Django 2.0.6 on 2018-06-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0012_ar_eh_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
