# Generated by Django 2.0.6 on 2018-07-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0014_auto_20180701_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOT_Q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(max_length=200)),
                ('op1', models.CharField(max_length=30)),
                ('op2', models.CharField(max_length=30)),
                ('op3', models.CharField(max_length=30)),
                ('op4', models.CharField(max_length=30)),
                ('ans', models.IntegerField(default=None)),
            ],
        ),
    ]
