# Generated by Django 2.0.6 on 2018-07-02 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0015_iot_q'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iot',
            options={'verbose_name_plural': 'IOT'},
        ),
    ]
