# Generated by Django 2.0.6 on 2018-07-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0016_auto_20180702_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IOT_Q',
        ),
    ]
